### Test
GET http://localhost:3000/health


### Get events
GET http://localhost:3000/events


### Get event by id
GET http://localhost:3000/events/3


### Set event
POST http://localhost:3000/events
Content-Type: application/json

{
  "Title": "Concert3",
	"Description": "Something3",
	"Location": "Somewhere3",
  "DateTime": "2025-01-01T08:00:00Z"
}


### Set event
PUT http://localhost:3000/events/5
Content-Type: application/json

{
  "Title": "Concert5",
	"Description": "Something5",
	"Location": "Somewhere5",
  "DateTime": "2025-01-01T08:00:00Z"
}
