### Test
GET http://localhost:3000/health


### Get events
GET http://localhost:3000/events


### Get event by id
GET http://localhost:3000/events/3


### Set event
POST http://localhost:3000/events
Content-Type: application/json

{
  "Title": "Concert2",
	"Description": "Something2",
	"Location": "Somewhere2",
  "DateTime": "2025-01-01T08:00:00Z"
}


### Update event
PUT http://localhost:3000/events/2
Content-Type: application/json

{
  "Title": "Concert updated",
	"Description": "Something updated",
	"Location": "Somewhere updated",
  "DateTime": "2025-01-01T08:00:00Z"
}
