### Get events
GET http://localhost:3000/events


### Get event by id
GET http://localhost:3000/events/2


### Set event
POST http://localhost:3000/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jbyIsImV4cCI6MTcwODkwOTMyOCwidXNlcklkIjoxfQ.nGVffnrLhjh9FjCVFfHShNyc9orlWgwu67fnmWaZpKM

{
  "Title": "Concert2",
	"Description": "Something",
	"Location": "Somewhere",
  "DateTime": "2025-01-01T08:00:00Z"
}


### Update event
PUT http://localhost:3000/events/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jbyIsImV4cCI6MTcwODkwOTMyOCwidXNlcklkIjoxfQ.nGVffnrLhjh9FjCVFfHShNyc9orlWgwu67fnmWaZpKM

{
  "Title": "Concert updated",
	"Description": "Something updated",
	"Location": "Somewhere updated",
  "DateTime": "2025-01-01T08:00:00Z"
}

### Delete event
DELETE http://localhost:3000/events/2
Content-Type: application/json
Authorization: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jbyIsImV4cCI6MTcwODkxMjM2NSwidXNlcklkIjo0fQ.eTB4lVMZ4izOy7_YbB83gPI5rjxciqjsi5JZ2bbaZnQ
