### Get users
GET http://localhost:3000/users


### Get user by id
GET http://localhost:3000/users/1


### Signup user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "Name": "Test User",
	"Email": "test@example.com",
	"Password": "Password1"
}


### Signin user
POST http://localhost:3000/users/signin
Content-Type: application/json

{
	"Email": "test@example.com",
	"Password": "Password1"
}


### Update user
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "Name": "Test",
	"Email": "example@test.com",
	"Password": "Password1"
}
